version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /examples/docusaurus
    schedule:
      interval: weekly
      day: monday
      time: "05:45"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: npm
    directory: /examples/docusaurus
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docusaurus
    groups:
      docusaurus-dependencies:
        patterns:
          - "*"
